[package]
name = "lua-config"
description = "A simple rust configuration tool using lua"
license = "MIT"
repository = "https://github.com/LeviLovie/lua-config"
version = "1.1.0"
edition = "2021"

[dependencies]
rlua = "0.20.1"
